name: discord-tools

type: nodejs:20

disk: 512

mounts:
  "logs":
    source: local
    source_path: logs

dependencies:
  nodejs:
    sharp: "*"

web:
  commands:
    start: "npm start"
  locations:
    /ws:
      passthru: true
